name: rustdesk

services:
  rustdesk-cp-api:
    image: cr.0xh4ck3d.dev/c/rustdesk-cp:latest
    restart: unless-stopped
    environment:
      SESSION_COOKIE_SECURE: true
      CONTROL_PLANE_DOMAIN: remote.swissy.shop
      DATABASE_URL: postgres://postgres:tJL4oW4NrIL8li67@db:6432/rustdesk
      BOOTSTRAP_TOKEN: 95077df3a731d57d0b36bf8ca9245ca1cc3227fb48c6518c30d90f9bd0d6a3a2
      BOOTSTRAP_CONFIG_SIGNING_KEY: 275ea38069c2468905bb30b6302a13d57b8aa19dc8ea58f46fee0c49fdd013d1
      SESSION_TTL_HOURS: 24
      DEVICE_CREDENTIAL_SIGNING_KEY: f148e21b69fc426422a2fcd803bd65a197e5106b5f3e3d458d1c865c06a4389b
      TOTP_ENCRYPTION_KEY: f53614fef8ff34a10245490ad1fde5caaf3bab41b71585360c7db02f89eb597a
      RUST_LOG: info,control_plane_api=info

  ruskdesk-cp-ui:
    image: cr.0xh4ck3d.dev/c/rustdesk-cp-ui:latest
    restart: unless-stopped

volumes:
  rustdesk-server-data:
