[package]
name = "control-plane-db"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
control-plane-domain = { path = "../domain" }
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
